name: Build custom Caddy-alpine image

on:
  workflow_dispatch:
    inputs:
      caddy_version:
        description: 'Caddy version (e.g. `2.10.0`...)'
        required: true
      build_number:
        description: 'Add build suffix to images with same Caddy version (e.g. leave empty or `-b1`, `-b2`...)'
        required: false

jobs:
  build-custom-caddy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=alpine
            type=semver,pattern={{version}}${{ inputs.build_number }}-alpine,value=${{ inputs.caddy_version }}
            type=semver,pattern={{major}}.{{minor}}${{ inputs.build_number }}-alpine,value=${{ inputs.caddy_version }}
            type=semver,pattern={{major}}${{ inputs.build_number }}-alpine,value=${{ inputs.caddy_version }}
      - name: Build and push alpine
        uses: docker/build-push-action@v6
        with:
          context: ./caddy
          file: Dockerfile.alpine
          build-args: |
            CADDY_VERSION=${{ inputs.caddy_version }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}